# This is a config for E2B sandbox template.
# You can use template ID (mzsphes266za7z5o1bbh) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("mzsphes266za7z5o1bbh") # Sync sandbox
# sandbox = await AsyncSandbox.create("mzsphes266za7z5o1bbh") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('mzsphes266za7z5o1bbh')

team_id = "6a135931-2076-4ef8-90e0-d58644927d02"
start_cmd = "/usr/local/bin/start-services.sh"
dockerfile = "template/e2b.docker.Dockerfile"
template_id = "mzsphes266za7z5o1bbh"
