# This is a config for E2B sandbox template.
# You can use template ID (pou9b3m5z92g2hafjxrl) or template name (cmux-devbox-docker) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("cmux-devbox-docker") # Sync sandbox
# sandbox = await AsyncSandbox.create("cmux-devbox-docker") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('cmux-devbox-docker')

template_id = "pou9b3m5z92g2hafjxrl"
dockerfile = "template/e2b.docker.Dockerfile"
template_name = "cmux-devbox-docker"
start_cmd = "/usr/local/bin/start-services.sh"
ready_cmd = "curl -sf http://localhost:39377/health || exit 1"
cpu_count = 8
memory_mb = 8_192
team_id = "aa31b299-02f6-4b38-b9d6-480698e0e377"
